"$schema" = 'https://starship.rs/config-schema.json'

format = """
[█](bright_red)\
$os\
$username\
[█](bg:bright_yellow fg:bright_red)\
$directory\
[█](fg:bright_yellow bg:bright_blue)\
$git_branch\
$git_status\
[█](fg:bright_blue bg:bright_green)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[█](fg:bright_green bg:bright_black)\
$docker_context\
$conda\
$pixi\
[█](fg:bright_black bg:base)\
$time\
[█ ](base)\
$line_break$character"""
palette = 'colorme'


[os]
disabled = false
style = "bg:bright_red fg:base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:bright_red fg:base"
style_root = "bg:bright_red fg:base"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:bright_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:bright_blue"
format = '[[ $symbol $branch ](fg:base bg:bright_blue)]($style)'

[git_status]
style = "bg:bright_blue"
format = '[[($all_status$ahead_behind )](fg:base bg:bright_blue)]($style)'

[nodejs]
symbol = ""
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[c]
symbol = " "
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[cpp]
symbol = " "
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[rust]
symbol = ""
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[golang]
symbol = ""
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[php]
symbol = ""
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[java]
symbol = ""
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[kotlin]
symbol = ""
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[haskell]
symbol = ""
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[python]
symbol = ""
style = "bg:bright_green"
format = '[[ $symbol( $version) ](fg:base bg:bright_green)]($style)'

[docker_context]
symbol = ""
style = "bg:bright_black"
format = '[[ $symbol( $context) ](fg:bright_blue bg:bright_black)]($style)'

[conda]
style = "bg:bright_black"
format = '[[ $symbol( $environment) ](fg:bright_blue bg:bright_black)]($style)'

[pixi]
style = "bg:bright_black"
format = '[[ $symbol( $version)( $environment) ](fg:text bg:bright_black)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:base"
format = '[[  $time ](fg:text bg:base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold bright_green)'
error_symbol = '[](bold bright_red)'
vimcmd_symbol = '[](bold bright_green)'
vimcmd_replace_one_symbol = '[](bold bright_magenta)'
vimcmd_replace_symbol = '[](bold bright_magenta)'
vimcmd_visual_symbol = '[](bold bright_yellow)'
