set -g mouse on 
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

source-file ~/.config/tmux/colorme.conf

bind v send-keys "vim" "Enter"
bind b display-popup -w 85% -h 85% -S "bg=default,fg=#{@colorme_fg}" -b rounded -E ~/.config/tmux/scripts/git-branch.sh
bind e display-popup -w 85% -h 85% -S "bg=default,fg=#{@colorme_fg}" -b rounded -E ~/.config/tmux/scripts/tmux-sess.sh
bind g display-popup -w 85% -h 85% -S "bg=default,fg=#{@colorme_fg}" -b rounded -E lazygit
bind d display-popup -w 85% -h 85% -S "bg=default,fg=#{@colorme_fg}" -b rounded -E lazydocker

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'

set-window-option -g popup-style "bg=default"

