set -g mouse on 
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind v send-keys "vim" "Enter"
bind b display-popup -w 85% -h 85% -S "bg=default,fg=#abb2bf" -b rounded -E ~/.config/tmux/scripts/git-branch.sh
bind e display-popup -w 85% -h 85% -S "bg=default,fg=#abb2bf" -b rounded -E ~/.config/tmux/scripts/tmux-sess.sh
bind g display-popup -w 85% -h 85% -S "bg=default,fg=#abb2bf" -b rounded -E lazygit
bind d display-popup -w 85% -h 85% -S "bg=default,fg=#abb2bf" -b rounded -E lazydocker
bind h display-popup -w 85% -h 85% -S "bg=default,fg=#abb2bf" -b rounded -E "gh dash"

set -g status-right-length 100
set -g status-left-length 100
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_disable_active_window_menu 'on'
set -g @rose_pine_variant 'dawn'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'rose-pine/tmux'
run '~/.tmux/plugins/tpm/tpm'

# Starship-style Pills
set -g status-style "bg=default"
setw -g window-status-style "bg=default"
setw -g window-status-current-style "bg=default"
set -g status-left "#[fg=#26233a,bg=default]#[bg=#26233a,fg=#c4a7e7,bold] 󰧱 #S #[fg=#26233a,bg=default] "
set -g status-right "#[fg=#26233a,bg=default]#[bg=#26233a,fg=#ebbcba] %I:%M%P 󰴈 #[fg=#26233a,bg=default] #[fg=#26233a,bg=default]#[bg=#26233a,fg=#9ccfd8] #h #[fg=#26233a,bg=default] "
set -g window-status-format "#[fg=#26233a,bg=default]#[bg=#26233a,fg=#e0def4] #I #W #[fg=#26233a,bg=default] "
set -g window-status-current-format "#[fg=#26233a,bg=default]#[bg=#26233a,fg=#f6c177,bold] #I #W #[fg=#26233a,bg=default] "
set -g window-status-separator " "

set-window-option -g popup-style "bg=default"
